import { ListingProperty } from "../types/listings";

export const STATIC_PROPERTIES: ListingProperty[] = [
  {
    id: "stow_001",
    title: "1236 Hibbard Dr",
    address: "1236 Hibbard Dr",
    city: "Stow",
    state: "OH",
    zipCode: "44224",
    price: 168000,
    beds: 3,
    baths: 1,
    sqft: 1176,
    propertyType: "Single Family",
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80",
    coordinates: { lat: 41.159, lng: -81.442 },
    yearBuilt: 1957,
    description: "Real data representation: Affordable ranch in Stow featuring updated flooring and cozy living spaces.",
    source: "realty_api",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "stow_002",
    title: "3891 Adaline Dr",
    address: "3891 Adaline Dr",
    city: "Stow",
    state: "OH",
    zipCode: "44224",
    price: 185000,
    beds: 3,
    baths: 1,
    sqft: 1056,
    propertyType: "Single Family",
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80",
    coordinates: { lat: 41.161, lng: -81.439 },
    yearBuilt: 1961,
    description: "Real data representation: Well-maintained 3-bedroom home with an expansive backyard and detached garage.",
    source: "realty_api",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "stow_003",
    title: "3568 Call Rd",
    address: "3568 Call Rd",
    city: "Stow",
    state: "OH",
    zipCode: "44224",
    price: 235000,
    beds: 4,
    baths: 2,
    sqft: 1605,
    propertyType: "Single Family",
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80",
    coordinates: { lat: 41.155, lng: -81.445 },
    yearBuilt: 1968,
    description: "Real data representation: Spacious split-level offering 4 bedrooms, dual living areas, and recent paint upgrades.",
    source: "realty_api",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "stow_004",
    title: "3186 Graham Rd (Duplex)",
    address: "3186 Graham Rd",
    city: "Stow",
    state: "OH",
    zipCode: "44224",
    price: 245000,
    beds: 4,
    baths: 2,
    sqft: 2010,
    propertyType: "Multi-Family",
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=800&q=80",
    coordinates: { lat: 41.169, lng: -81.440 },
    yearBuilt: 1974,
    description: "Real data representation: Prime duplex investment in Stow! Fully occupied side-by-side units, close to commerce.",
    source: "realty_api",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "stow_005",
    title: "3543 Elm Rd",
    address: "3543 Elm Rd",
    city: "Stow",
    state: "OH",
    zipCode: "44224",
    price: 205000,
    beds: 3,
    baths: 2,
    sqft: 1296,
    propertyType: "Single Family",
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?auto=format&fit=crop&w=800&q=80",
    coordinates: { lat: 41.165, lng: -81.448 },
    yearBuilt: 1971,
    description: "Real data representation: Turnkey home with a modern kitchen, luxury vinyl flooring, and finished lower level.",
    source: "realty_api",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: "stow_006",
    title: "1864 Liberty Rd",
    address: "1864 Liberty Rd",
    city: "Stow",
    state: "OH",
    zipCode: "44224",
    price: 242000,
    beds: 3,
    baths: 2,
    sqft: 1400,
    propertyType: "Single Family",
    status: "Active",
    imageUrl: "https://images.unsplash.com/photo-1510627498534-cf7e9002facc?auto=format&fit=crop&w=800&q=80",
    coordinates: { lat: 41.150, lng: -81.450 },
    yearBuilt: 1965,
    description: "Real data representation: Classic Stow traditional home featuring beautiful landscaping and an attached two-car garage.",
    source: "realty_api",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];
